/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedExec: typeof import('./components/AdvancedExec.vue')['default']
    AdvancedGrid: typeof import('./components/AdvancedGrid.vue')['default']
    AdvancedScan: typeof import('./components/AdvancedScan.vue')['default']
    AppShell: typeof import('./components/AppShell.vue')['default']
    ConfigPage: typeof import('./components/ConfigPage.vue')['default']
    CtrlAside: typeof import('./components/CtrlAside.vue')['default']
    Field: typeof import('./components/Field.vue')['default']
    LiveLists: typeof import('./components/LiveLists.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    PairList: typeof import('./components/PairList.vue')['default']
    TapePage: typeof import('./components/TapePage.vue')['default']
  }
}
