/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdvancedBurst: typeof import('./components/AdvancedBurst.vue')['default']
    AdvancedExec: typeof import('./components/AdvancedExec.vue')['default']
    AdvancedGrid: typeof import('./components/AdvancedGrid.vue')['default']
    AdvancedScan: typeof import('./components/AdvancedScan.vue')['default']
    AppShell: typeof import('./components/AppShell.vue')['default']
    ConfigPage: typeof import('./components/ConfigPage.vue')['default']
    CtrlAside: typeof import('./components/CtrlAside.vue')['default']
    Field: typeof import('./components/Field.vue')['default']
    LiveLists: typeof import('./components/LiveLists.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    PairList: typeof import('./components/PairList.vue')['default']
    ScanHeadHint: typeof import('./components/ScanHeadHint.vue')['default']
    ScanPage: typeof import('./components/ScanPage.vue')['default']
    TapePage: typeof import('./components/TapePage.vue')['default']
  }
}
